/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function runGenerate(configPath?: string | undefined | null, cliKey?: string | undefined | null): void

export declare function runRead(filePath?: string | undefined | null, cliKey?: string | undefined | null, configPath?: string | undefined | null): string
